import Head from "next/head";
import React from "react";
import { GiMagnifyingGlass } from "react-icons/gi";
import Content from "../../components/Content";
import Header from "../../components/Header";
import Navbar from "../../components/Navbar";
import Type from "../../components/Type";
import classes from "../../styles/WebDesign.module.css";
import classes2 from "../../styles/DigitalMarketing.module.css";
import ReviewsSection from "../../sections/ReviewsSection";
import Footer from "../../components/Footer";
import { RiBookletLine, RiTodoLine } from "react-icons/ri";
import { BiCoinStack } from "react-icons/bi";
import { TbMessages } from "react-icons/tb";
import { BsBox } from "react-icons/bs";
import Variety from "../../components/Variety";
import { FaLocationArrow } from "react-icons/fa";

const contentCreation = () => {
	return (
		<div>
			<Head>
				<title>The Site Space</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<Navbar />
			<Header
				text1="Digital"
				gradient1="Content"
				gradient2="Creation"
				text2="Agency."
				space="&nbsp;"
				bgText1="Content"
				bgText2="Creation"
				description="SEO optimised content that helps businesses improve their Google search rankings. A talented team of copy writing experts in London."
			/>
			<section className={classes.typesSection}>
				<div className={classes.types}>
					<Type icon={<RiBookletLine />} name="Brief on Content & Topics" />
					<Type icon={<BiCoinStack />} name="Research & Data Gathering" />
					<Type icon={<RiTodoLine />} name="Unique Content Creation" />
					<Type icon={<TbMessages />} name="Plagiarism & QA" />
					<Type icon={<BsBox />} name="Delivery & Implementation" />
				</div>
				<Content
					title="How a great content can help?"
					description="Great content means higher search results on search engines. Web Buds create unique and SEO optimized content that helps websites improve their rankings and enable Google spiders to crawl the website and establish their position among search results."
				/>
			</section>
			<section className={classes.varietiesSection}>
				<Variety
					title="SEO Professionals"
					icon={<FaLocationArrow />}
					description="Out content writing team is fully trained and is always up to date with the latest Google updated and SEO techniques and trends."
				/>
				<Variety
					title="In House Content Writers"
					icon={<FaLocationArrow />}
					description="Out content writing team is fully trained and is always up to date with the latest Google updated and SEO techniques and trends."
				/>
				<Variety
					title="Expert Bloggers"
					icon={<FaLocationArrow />}
					description="Out content writing team is fully trained and is always up to date with the latest Google updated and SEO techniques and trends."
				/>
			</section>
			<section className={classes2.workSection}>
				<h1>What we do for you?</h1>
				<p>
					SEO is not straightforward and not an easy process. It's takes time to
					rank a website on top of Google searches. We use agile SEO techniques
					to rank websites and what we do is amazing. SEO need regular work to
					stay on top of your competition, and every website needs a digital
					marketing strategy; otherwise, it will fall behind and not generate
					any business. We use industry-leading tools for reporting and daily
					optimization. Our specialists monitor the campaign's performance every
					day and make changes to the strategy wherever required.
				</p>
				<div className={classes2.workTypes}>
					<Type icon={<GiMagnifyingGlass />} name="SEO" />
					<Type icon={<GiMagnifyingGlass />} name="Social Media Marketing" />
					<Type icon={<GiMagnifyingGlass />} name="Local SEO" />
					<Type icon={<GiMagnifyingGlass />} name="PPC Google Ads" />
				</div>
			</section>
			<ReviewsSection />
			<Footer />
		</div>
	);
};

export default contentCreation;
