import React from "react";
import Head from "next/head";
import Header from "../../components/Header";
import Navbar from "../../components/Navbar";
import classes from "../../styles/WebDesign.module.css";
import classes2 from "../../styles/DigitalMarketing.module.css";
import Type from "../../components/Type";
import Content from "../../components/Content";
import Variety from "../../components/Variety";
import { GiMagnifyingGlass, GiTargetShot } from "react-icons/gi";
import ReviewsSection from "../../sections/ReviewsSection";
import Footer from "../../components/Footer";
import { FiRefreshCcw } from "react-icons/fi";
import { FaLocationArrow, FaTv } from "react-icons/fa";
import { ImMap2 } from "react-icons/im";
import { AiOutlineMobile } from "react-icons/ai";

const digitalMarketing = () => {
	return (
		<div>
			<Head>
				<title>The Site Space</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<Navbar />
			<Header
				text1="Digital"
				gradient1="Marketing"
				text2="Agency London."
				bgText1="Digital"
				bgText2="Marketing"
				description="Get your website ranked on the 1st page of Google with our guaranteed 1st page Google ranking service, get your website ahead of your competitors for your desired keywords."
			/>
			<section className={classes.typesSection}>
				<div className={classes.types}>
					<Type
						icon={<GiMagnifyingGlass />}
						name="Technical SEO & Website Analysis"
					/>
					<Type icon={<FiRefreshCcw />} name="Keywords & Competitor Analysis" />
					<Type
						icon={<GiTargetShot />}
						name="On-Page SEO & Metas Integration"
					/>
					<Type
						icon={<FaLocationArrow />}
						name="Off-Page SEO & Google Submission"
					/>
					<Type icon={<ImMap2 />} name="Monthly Reporting" />
				</div>
				<Content
					title="SEO Service for everyone."
					description="Increase your web outreach with our powerful digital marketing strategies. Our affordable SEO services have helped many businesses to lift their feet off the ground with our SEO services. We create high quality SEO backlinks, this makes SEO marketing highly effective."
				/>
			</section>
			<section className={classes.varietiesSection}>
				<Variety
					title="Technical SEO"
					icon={<GiMagnifyingGlass />}
					description="	A simple website to showcase your services or tell your clients what
					you do. A brochure website will be best for you."
				/>
				<Variety
					title="On-Page SEO"
					icon={<GiMagnifyingGlass />}
					description="	A simple website to showcase your services or tell your clients what
					you do. A brochure website will be best for you."
				/>
				<Variety
					title="Off-Page SEO"
					icon={<GiMagnifyingGlass />}
					description="	A simple website to showcase your services or tell your clients what
					you do. A brochure website will be best for you."
				/>
			</section>
			<section className={classes2.workSection}>
				<h1>What we do for you?</h1>
				<p>
					SEO is not straightforward and not an easy process. It's takes time to
					rank a website on top of Google searches. We use agile SEO techniques
					to rank websites and what we do is amazing. SEO need regular work to
					stay on top of your competition, and every website needs a digital
					marketing strategy; otherwise, it will fall behind and not generate
					any business. We use industry-leading tools for reporting and daily
					optimization. Our specialists monitor the campaign's performance every
					day and make changes to the strategy wherever required.
				</p>
				<div className={classes2.workTypes}>
					<Type icon={<GiMagnifyingGlass />} name="SEO" />
					<Type icon={<AiOutlineMobile />} name="Social Media Marketing" />
					<Type icon={<FaLocationArrow />} name="Local SEO" />
					<Type icon={<FaTv />} name="PPC Google Ads" />
				</div>
			</section>
			<ReviewsSection />
			<Footer />
		</div>
	);
};

export default digitalMarketing;
