import React from "react";
import Head from "next/head";
import Header from "../../components/Global/Header";
import Navbar from "../../components/Global/Navbar";
import classes from "../../styles/WebDesign/WebDesign.module.css";
import Type from "../../components/WebDesign/Type";
import Content from "../../components/WebDesign/Content";
import { RiBookletLine } from "react-icons/ri";
import Variety from "../../components/WebDesign/Variety";
import { BsLaptop } from "react-icons/bs";

const digitalMarketing = () => {
	return (
		<div>
			<Head>
				<title>The Site Space</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<Navbar />
			<Header
				text1="Digital"
				gradient1="Marketing"
				text2="Agency London."
				bgText1="Digital"
				bgText2="Marketing"
				description="Get your website ranked on the 1st page of Google with our guaranteed 1st page Google ranking service, get your website ahead of your competitors for your desired keywords."
			/>
			<section className={classes.typesSection}>
				<div className={classes.types}>
					<Type icon={<RiBookletLine />} name="Project" />
					<Type icon={<RiBookletLine />} name="Prototyping" />
					<Type icon={<RiBookletLine />} name="Development" />
					<Type icon={<RiBookletLine />} name="Testing" />
					<Type icon={<RiBookletLine />} name="Delivery" />
				</div>
				<Content
					title="SEO Service for everyone."
					description="Increase your web outreach with our powerful digital marketing strategies. Our affordable SEO services have helped many businesses to lift their feet off the ground with our SEO services. We create high quality SEO backlinks, this makes SEO marketing highly effective."
				/>
			</section>
			<section className={classes.varietiesSection}>
				<Variety
					title="Technical SEO"
					icon={<BsLaptop />}
					description="	A simple website to showcase your services or tell your clients what
					you do. A brochure website will be best for you."
				/>
				<Variety title="On-Page SEO" icon={<BsLaptop />} />
				<Variety title="Off-Page SEO" icon={<BsLaptop />} />
			</section>
		</div>
	);
};

export default digitalMarketing;
