import React from "react";
import Head from "next/head";
import Header from "../../components/Header";
import Navbar from "../../components/Navbar";

const mobileApp = () => {
	return (
		<div>
			<Head>
				<title>The Site Space</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<Navbar />
			<Header
				text1="Mobile"
				gradient1="Application"
				gradient2="Development"
				text2="Company."
				bgText1="Mobile"
				bgText2="Application"
				space="&nbsp;"
				description="Our experienced app developers create modern, high end apps that put your business right in front of your audience's hands."
			/>
		</div>
	);
};

export default mobileApp;
