import Head from "next/head";
import React from "react";
import { AiOutlineLaptop, AiOutlineMobile } from "react-icons/ai";
import { BsBox } from "react-icons/bs";
import { FiSettings } from "react-icons/fi";
import { RiBookletLine } from "react-icons/ri";
import Footer from "../../components/Global/Footer";
import Header from "../../components/Global/Header";
import Navbar from "../../components/Global/Navbar";
import Type from "../../components/WebDesign/Type";
import ReviewsSection from "../../sections/HomePage/ReviewsSection";
import classes from "../../styles/WebDesign/WebDesign.module.css";
import classes2 from "../../styles/DigitalMarketing/DigitalMarketing.module.css";
import classes3 from "../../styles/UIUX/UIUX.module.css";
import { GiMagnifyingGlass } from "react-icons/gi";
import { FaLocationArrow, FaTv } from "react-icons/fa";

const UIUX = () => {
	return (
		<div>
			<Head>
				<title>The Site Space</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<Navbar />
			<Header
				text1="Creative"
				gradient1="Design"
				text2="Agency London."
				bgText1="Branding"
				bgText2="UI-UX Design"
				description="Great design means great online presence. People buy what they see so if you want to sell more then give your brand a strong online identity.."
			/>
			<section className={classes.typesSection}>
				<div className={classes.types}>
					<Type icon={<RiBookletLine />} name="Design Briefs & Meetings" />
					<Type icon={<AiOutlineMobile />} name="Sketching & Prototyping" />
					<Type icon={<AiOutlineLaptop />} name="Design Presentations" />
					<Type icon={<FiSettings />} name="Changes & Revisions" />
					<Type icon={<BsBox />} name="Delivery & Impleme tation" />
				</div>
			</section>
			<section className={classes3.howSection1}>
				<h1>How a branding & UI experts can help?</h1>
				<p>
					At Web Buds, we deliver great brand experiences and designs to some of
					the industry leaders in tech, finance, retail and professional
					sectors. From business branding to rebuilding websites and designs our
					deep understanding, experience and market research means we can
					dedicate our creative energy in producing creative designs and deliver
					distinctive designing solutions.
				</p>
			</section>
			<section className={classes3.howSection2}>
				<h1>What we do for you?</h1>
				<p>
					SEO is not straightforward and not an easy process. It's takes time to
					rank a website on top of Google searches. We use agile SEO techniques
					to rank websites and what we do is amazing. SEO need regular work to
					stay on top of your competition, and every website needs a digital
					marketing strategy; otherwise, it will fall behind and not generate
					any business. We use industry-leading tools for reporting and daily
					optimization. Our specialists monitor the campaign's performance every
					day and make changes to the strategy wherever required.
				</p>
				<div className={classes2.workTypes}>
					<Type icon={<GiMagnifyingGlass />} name="SEO" />
					<Type icon={<AiOutlineMobile />} name="Social Media Marketing" />
					<Type icon={<FaLocationArrow />} name="Local SEO" />
					<Type icon={<FaTv />} name="PPC Google Ads" />
				</div>
			</section>
			<ReviewsSection />
			<Footer />
		</div>
	);
};

export default UIUX;
