import Head from "next/head";
import React from "react";
import Header from "../../components/Global/Header";
import Navbar from "../../components/Global/Navbar";

const webDesign = () => {
	return (
		<div>
			<Head>
				<title>The Site Space</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<Navbar />
			<Header
				text1="Creative"
				gradient1="Website"
				text2="Design."
				bgText1="Creative"
				bgText2="Website"
				description="A team of creative web designers in London who offers best web design, honest advice and a great work portfolio."
			/>
		</div>
	);
};

export default webDesign;
