import Head from "next/head";
import React from "react";
import Footer from "../../components/Footer";
import Header from "../../components/Header";
import Navbar from "../../components/Navbar";
import ReviewsSection from "../../sections/ReviewsSection";
import WorkSection from "../../sections/WorkSection";
import TypesSection from "../../sections/TypesSection";
import VarietiesSection from "../../sections/VarietiesSection";

const WebDesign = () => {
	return (
		<div>
			<Head>
				<title>The Site Space</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<Navbar />
			<Header
				text1="Creative"
				gradient1="Website"
				text2="Design."
				bgText1="Creative"
				bgText2="Website"
				description="A team of creative web designers in London who offers best web design, honest advice and a great work portfolio."
			/>
			<TypesSection />
			<VarietiesSection />
			<WorkSection />
			<ReviewsSection />
			<Footer />
		</div>
	);
};

export default WebDesign;
