import React from "react";
import request, { gql } from "graphql-request";
import Head from "next/head";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import { getProjects } from "../index";
import classes from "../../styles/SingleProject.module.css";

const graphqlAPI = process.env.NEXT_PUBLIC_GRAPHCMS_ENDPOINT;

export const getProjectDetails = async (slug) => {
	const query = gql`
		query GetProjectDetails($slug: String!) {
			project(where: { slug: $slug }) {
				id
				title
				image {
					url
				}
				description
				reverse
				slug
				overview
				industry
				involvement
				location
				showcaseImage1 {
					url
				}
				showcaseImage2 {
					url
				}
				mainImage {
					url
				}
				mobileImage {
					url
				}
			}
		}
	`;

	const result = await request(graphqlAPI, query, { slug });
	return result.project;
};

export async function getStaticProps({ params }) {
	const project = await getProjectDetails(params.slug);
	return {
		props: {
			project,
		},
	};
}

export async function getStaticPaths() {
	const projects = await getProjects();
	return {
		paths: projects.map((project) => {
			return {
				params: {
					slug: project.slug,
				},
			};
		}),
		fallback: false,
	};
}

const SingleProject = ({ project }) => {
	return (
		<>
			<Head>
				<title>The Site Space</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<Navbar />
			<div className={classes.singleProject}>
				<div className={classes.header}>
					<div className={classes.left}>
						<h2>{project.title}</h2>
						<p>{project.overview}</p>
						<div className={classes.info}>
							<div>
								<h3>Industry</h3>
								<p>{project.industry}</p>
							</div>
							<div>
								<h3>Location</h3>
								<p>{project.location}</p>
							</div>
							<div>
								<h3>Involvement</h3>
								<p className={classes.involvement}>{project.involvement}</p>
							</div>
						</div>
					</div>
					<div className={classes.right}>
						<img src={project.image.url} alt={project.title} />
						<button className={`circleBtn ${classes.visitBtn}`}>
							Visit Website
						</button>
					</div>
				</div>
				<div className={classes.showcase}>
					<div className={classes.showcaseImage}>
						<img src={project.showcaseImage1.url} alt={project.title} />
					</div>
					<div className={classes.showcaseImage}>
						<img src={project.showcaseImage2.url} alt={project.title} />
					</div>
				</div>
				<div className={classes.mainImage}>
					<img src={project.mainImage.url} alt={project.title} />
				</div>
				<div className={classes.mobileImage}>
					<img src={project.mobileImage.url} alt={project.title} />
				</div>
			</div>
			<Footer />
		</>
	);
};

export default SingleProject;
