import React from "react";
import request, { gql } from "graphql-request";
import Head from "next/head";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import { getProjects } from "../index";
import classes from "../../styles/SingleProject.module.css";

const graphqlAPI = process.env.NEXT_PUBLIC_GRAPHCMS_ENDPOINT;

export const getProjectDetails = async (slug) => {
	const query = gql`
		query GetProjectDetails($slug: String!) {
			project(where: { slug: $slug }) {
				id
				title
				image {
					url
				}
				description
				reverse
				slug
			}
		}
	`;

	const result = await request(graphqlAPI, query, { slug });
	return result.project;
};

export async function getStaticProps({ params }) {
	const project = await getProjectDetails(params.slug);
	return {
		props: {
			project,
		},
	};
}

export async function getStaticPaths() {
	const projects = await getProjects();
	return {
		paths: projects.map((project) => {
			return {
				params: {
					slug: project.slug,
				},
			};
		}),
		fallback: false,
	};
}

const SingleProject = ({ project }) => {
	console.log(project);
	return (
		<>
			<Head>
				<title>The Site Space</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<Navbar />
			<div>
				<h1>{project.title}</h1>
			</div>
			<Footer />
		</>
	);
};

export default SingleProject;
