import Head from "next/head";
import React from "react";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import classes from "../styles/AboutUs.module.css";

const aboutUs = () => {
	return (
		<div>
			<Head>
				<title>The Site Space</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<Navbar />
			<section className={classes.aboutSection}>
				<h1>
					A team of young and <br />{" "}
					<span className={classes.gradient}>talented digital experts</span>
				</h1>
				<p>
					Web Buds is a team of young, talented and fast-growing digital experts
					specialising in modern website design and development and effective
					digital marketing and search engine optimization techniques.
				</p>
				<p>
					We are based in the heart of London, inspired by the online creative
					community. We understand all the latest design and development trends.
				</p>
				<p>
					Our team uses all the modern tools and provide detailed reports.
					Unlike others, our experts provide the services and also love
					educating our clients about the results and what they will be getting
					at the end.
				</p>
				<p>
					Whether you need a stunning mobile responsive website or a
					high-performing digital marketing campaign? A website that loads
					quickly, engage visitors, and helps in your business growth?
				</p>
				<p>Talk to us, and we will make it happen.</p>
			</section>
			<Footer />
		</div>
	);
};

export default aboutUs;
