import Head from "next/head";
import React from "react";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";
import "react-tabs/style/react-tabs.css";
import classes from "../styles/Blogs.module.css";
import BlogCard from "../components/BlogCard";

const blogs = () => {
	return (
		<div>
			<Head>
				<title>The Site Space</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<Navbar />
			<Header
				text1="News"
				gradient1="Insights, And"
				gradient2="Creative Culture"
				text2="from the Site Space."
				bgText1="The Site"
				bgText2="Space"
				space="&nbsp;"
			/>
			<section className={classes.cardsSection}>
				<Tabs>
					<TabList>
						<Tab>All</Tab>
						<Tab>Website</Tab>
						<Tab>E-commerce</Tab>
						<Tab>SEO</Tab>
						<Tab>Digital Marketing</Tab>
						<Tab>Ui Design</Tab>
						<Tab>Trending</Tab>
					</TabList>

					<TabPanel>
						<BlogCard />
						<BlogCard />
						<BlogCard />
						<BlogCard />
						<BlogCard />
						<BlogCard />
						<BlogCard />
						<BlogCard />
						<BlogCard />
					</TabPanel>
					<TabPanel>
						<BlogCard />
						<BlogCard />
						<BlogCard />
					</TabPanel>
					<TabPanel>
						<BlogCard />
						<BlogCard />
						<BlogCard />
					</TabPanel>
					<TabPanel>
						<BlogCard />
						<BlogCard />
						<BlogCard />
					</TabPanel>
					<TabPanel>
						<BlogCard />
						<BlogCard />
						<BlogCard />
					</TabPanel>
					<TabPanel>
						<BlogCard />
						<BlogCard />
						<BlogCard />
					</TabPanel>
					<TabPanel>
						<BlogCard />
						<BlogCard />
						<BlogCard />
					</TabPanel>
				</Tabs>
			</section>
			<Footer />
		</div>
	);
};

export default blogs;
