import Head from "next/head";
import React from "react";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Navbar from "../components/Navbar";

const blogs = () => {
	return (
		<div>
			<Head>
				<title>The Site Space</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<Navbar />
			<Header
				text1="News"
				gradient1="Insights, And"
				gradient2="Creative Culture"
				text2="from the Site Space."
				bgText1="The Site"
				bgText2="Space"
				space="&nbsp;"
			/>
			<Footer />
		</div>
	);
};

export default blogs;
