import Head from "next/head";
import React from "react";
import { AiOutlineInstagram, AiOutlineTwitter } from "react-icons/ai";
import { FaFacebookF, FaLinkedinIn } from "react-icons/fa";
import Navbar from "../components/Navbar";
import classes from "../styles/ContactUs.module.css";

const contactUs = () => {
	return (
		<div>
			<Head>
				<title>The Site Space</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<div className={classes.blobs}>
				<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
					<path
						fill="#4998C3"
						d="M56,-67C71.9,-53.4,83.7,-35.1,87,-15.5C90.3,4.2,85.1,25.2,74.8,43.3C64.5,61.4,49,76.7,30.3,83.8C11.6,90.8,-10.3,89.6,-29.8,82.4C-49.4,75.1,-66.5,61.7,-77,44.2C-87.5,26.6,-91.3,4.9,-86.9,-14.6C-82.6,-34.1,-70.1,-51.4,-54.3,-65C-38.4,-78.6,-19.2,-88.5,0.4,-89C20,-89.5,40.1,-80.5,56,-67Z"
						transform="translate(100 100)"
					/>
				</svg>
				<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
					<path
						fill="#EC4D37"
						d="M56,-67C71.9,-53.4,83.7,-35.1,87,-15.5C90.3,4.2,85.1,25.2,74.8,43.3C64.5,61.4,49,76.7,30.3,83.8C11.6,90.8,-10.3,89.6,-29.8,82.4C-49.4,75.1,-66.5,61.7,-77,44.2C-87.5,26.6,-91.3,4.9,-86.9,-14.6C-82.6,-34.1,-70.1,-51.4,-54.3,-65C-38.4,-78.6,-19.2,-88.5,0.4,-89C20,-89.5,40.1,-80.5,56,-67Z"
						transform="translate(100 100)"
					/>
				</svg>
			</div>
			<Navbar />
			<section className={classes.contactSection}>
				<div className={classes.left}>
					<h1>
						Feel free to <br /> get in touch
					</h1>
					<div className={classes.linksContainer}>
						<div className={classes.links}>
							<AiOutlineInstagram />
							<FaLinkedinIn />
							<AiOutlineTwitter />
							<FaFacebookF />
						</div>
						<a href="mailto:info@thesitespace.com">info@thesitespace.com</a>
					</div>
					<h2>London</h2>
					<p>Unit 208</p>
					<p>Pill Box Studios</p>
					<p>115 Coventry Rd</p>
					<p>London</p>
					<p>E2 6GG</p>
				</div>
				<div className={classes.right}>
					<h2>
						Let's Create <br /> Something Magical
					</h2>
					<form className={classes.form}>
						<input type="text" placeholder="Name" className={classes.input} />
						<input type="email" placeholder="Email" className={classes.input} />
						<input
							type="text"
							placeholder="Contact number"
							className={classes.input}
						/>
						<input
							type="text"
							placeholder="Business name"
							className={classes.input}
						/>
						<input
							type="text"
							placeholder="Current website"
							className={classes.input}
						/>
						<input
							type="text"
							placeholder="Type your message"
							className={classes.input}
						/>
						<div className={classes.submitBtnContainer}>
							<button className={`circleBtn ${classes.submitBtn}`}>
								Submit
							</button>
						</div>
					</form>
				</div>
			</section>
		</div>
	);
};

export default contactUs;
