import Head from "next/head";
import React from "react";
import { AiOutlineInstagram, AiOutlineTwitter } from "react-icons/ai";
import { FaFacebookF, FaLinkedinIn } from "react-icons/fa";
import Navbar from "../components/Navbar";
import classes from "../styles/ContactUs.module.css";

const contactUs = () => {
	return (
		<div>
			<Head>
				<title>The Site Space</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<Navbar />
			<section className={classes.contactSection}>
				<div className={classes.left}>
					<h1>
						Feel free to <br /> get in touch
					</h1>
					<div className={classes.linksContainer}>
						<div className={classes.links}>
							<AiOutlineInstagram />
							<FaLinkedinIn />
							<AiOutlineTwitter />
							<FaFacebookF />
						</div>
						<p>enquiries@thesitespace.com</p>
					</div>
					<h2>London</h2>
					<p>Unit 208</p>
					<p>Pill Box Studios</p>
					<p>115 Coventry Rd</p>
					<p>London</p>
					<p>E2 6GG</p>
				</div>
				<div className={classes.right}>
					<h2>
						Let's Create <br /> Something Magical
					</h2>
					<form className={classes.form}>
						<input type="text" placeholder="Name" className={classes.input} />
						<input type="email" placeholder="Email" className={classes.input} />
						<input
							type="text"
							placeholder="Contact number"
							className={classes.input}
						/>
						<input
							type="text"
							placeholder="Business name"
							className={classes.input}
						/>
						<input
							type="text"
							placeholder="Current website"
							className={classes.input}
						/>
						<input
							type="text"
							placeholder="Type your message"
							className={classes.input}
						/>
					</form>
				</div>
			</section>
		</div>
	);
};

export default contactUs;
