import Head from "next/head";
import Header from "../components/Global/Header";
import Navbar from "../components/Global/Navbar";
import AboutSection from "../sections/HomePage/AboutSection";
import ReviewsSection from "../sections/HomePage/ReviewsSection";
import ServicesSection from "../sections/HomePage/ServicesSection";
import WorkSection from "../sections/HomePage/WorkSection";

export default function Home() {
	return (
		<div>
			<Head>
				<title>The Site Space</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<Navbar />
			<Header />
			<AboutSection />
			<WorkSection />
			<ServicesSection />
			<ReviewsSection />
		</div>
	);
}
